[workspace]
members = [
    "crates/core",
    "crates/mbql",
    "crates/crypto",
    "crates/util",
    "crates/mbcli",
    "crates/genesis",
    "crates/kgraph",
    "crates/store"
]

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[profile.test.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16